# Use golang:1.22 as the builder stage
FROM golang:1.22 as builder

# Set the working directory
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download all dependencies (go.sum may be empty if there are no dependencies)
RUN go mod download

# Copy the source code
COPY . .

# Build the Go executable for amd64 architecture
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/drone-ant-plugin ./main.go

# Use Alpine Linux as the base image for the final stage
FROM alpine:latest

# Install Ant using apk
RUN apk update && \
    apk add --no-cache openjdk8 && \
    apk add --no-cache apache-ant

# Set the working directory inside the container
WORKDIR /app

# Copy the built Go executable from the builder stage to the final stage
COPY --from=builder /app/drone-ant-plugin /app/

# Set the entrypoint to the Go executable
ENTRYPOINT ["/app/drone-ant-plugin"]
